# Make sure to check the documentation at https://goreleaser.com
project_name: azure-openai-proxy
env:
  - GIT_URL=https://github.com/stulzq/azure-openai-proxy
before:
  hooks:
    - go mod tidy
builds:
  - id: azure-openai-proxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    main: ./cmd
    binary: azure-openai-proxy
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.buildDate={{ .Date }}
      - -X main.gitCommit={{ .Commit }}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^build:'
      - '^ci:'
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^feat(deps):'
